FROM dockerfile/nodejs

ENV PATH /poputchiki/node_modules/.bin:$PATH

# installing saas
RUN apt-get install ruby -y
RUN gem install sass

# cloning project
ADD . /poputchiki
WORKDIR /poputchiki

# installing deps
RUN npm install
RUN npm install sass jade clientjade -g

# compiling static
RUN ./compile.sh

RUN mkdir /static
VOLUME /static
ADD start.sh /start.sh
# copy files on start
ENTRYPOINT sh /start.sh
